name: CI

on:
  pull_request:
    branches: [ master, staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: pylint-and-format
        uses: itsvinayak/pylint-and-format@v1.1


